### ISSUE TITLE
Is there a bug in the glxext.h file?

### ISSUE THREAD

**Issue by ioakimidis** [hlrs-vis/covise#12]
Dear all,

i would appreciate a response to the following error message I get after typing 'make'. It seems to be something wrong in the glxext.h file. Is there an elegant solution to this?

[ 13%] Building CXX object src/3rdparty/deskvox/virvo/virvo/CMakeFiles/virvo.dir/vvbsptree.cpp.o
In file included from /usr/include/GL/glx.h:333:0,
                 from /home/konstantin/Workspace/covise/src/3rdparty/deskvox/virvo/virvo/vvopengl.h:42,
                 from /home/konstantin/Workspace/covise/src/3rdparty/deskvox/virvo/virvo/vvbsptree.cpp:27:
/usr/include/GL/glxext.h:480:143: error: ‘GLintptr’ has not been declared
 typedef void ( *PFNGLXCOPYBUFFERSUBDATANVPROC) (Display *dpy, GLXContext readCtx, GLXContext writeCtx, GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
                                                                                                                                               ^

Just for the record I'm on Ubuntu 14.10 (Utopic Unicorn)

Best regards,

KI

**Comment by aumuell** [comment]
Thank you for the report!

Probably not caused or fixable from within COVISE, opened a new issue for DeskVOX: https://github.com/deskvox/deskvox/issues/2

**Comment by aumuell** [comment]
Dear KI,

please do `git pull && git submodule sync && git submodule update --init` to make sure to have a version of virvo with a possible fix.
