### ISSUE TITLE
OpenCOVER display issues

### ISSUE THREAD

**Issue by legts** [hlrs-vis/covise#15]
Hello,

 I can open up and display basic X11 apps like xterm but when I launch opencover, I get these errors about the display. ( I assume not finding that one plugin is not a show stopper ). Any advice ? Thanks again in advance!

502] [hxgpu0] $opencover 
_exec_for_covise
OpenCOVER: Starting up

Compiled with OpenMP support, using a maximum of 1 threads
Input: Persons must be configured!
plugins: const
devices:
buttons: Mouse
bodies:
persons: num=1, active=default, head=0, hand=0
Loading plugins: SGBrowser Vrml97 ClipPlane PLMXML ALVAR/hx/u/legts/covise/pangolin/lib/OpenCOVER/plugins/libALVAR.so: cannot open shared object file: No such file or directory

libALVAR.so: cannot open shared object file: No such file or directory
ERROR: could not load shared Library libALVAR.so
.
Plugins which failed to load: ALVAR.
Error: Unable to open display ":0.0".
No valid Pixel Format found, trying without multisample Buffer
Error: Unable to open display ":0.0".
No valid Pixel Format found, trying without stencil
Error: Unable to open display ":0.0".
No valid Pixel Format found, trying without alpha
Error: Unable to open display ":0.0".
VRWindow::createWin 0 --- finished
window 0 of screen 0 not defined
A Unable to open display ":0.-1"
Viewer::realize() - failed to set up any windows
PLMXMLPlugin::PLMXMLPlugin
host: localhost, port: 31231
connecting to audio server "localhost" at port 31231...connecting socket failed: Connection refused
OpenCOVER: Shutting down

Unloading plugins: ClipPlane PLMXML SGBrowser Vrml97destruction of 0 sources

**Comment by aumuell** [comment]
The X11 display OpenCOVER tries to open is not controlled by the `DISPLAY` environment variable but by the settings in its configuration file, typically `$COVISEDIR/config/config.xml`. Could it be that you are accessing the machine where you try to start OpenCOVER remotely via SSH and your `DISPLAY` is set accordingly? This would explain why `xterm` works.

For efficient OpenGL rendering you should start OpenCOVER on the machine where you have your display device connected. But you also have to configure the X server on that machine such that OpenCOVER is allowed to access it. If you share the machine only with trusted users, something like `xhost +LOCAL:` directly after the X server has been started, should help. Where you have to put such a command depends on your display manager (XDM, KDM, LightDM, ...).

**Comment by legts** [comment]
Yes, I am accessing the machine that I am trying to run OpenCOVER on via SSH.  I will attempt to configure the X server so that OpenCOVER is allowed to access it!  I will keep you updated.

**Comment by legts** [comment]
Thanks for the help, but we're still having troubles!  Maybe it would help to explain our setup.  We are running OpenCOVER on a machine named "hxgpu0".  Our display is running on a machine called "hxv142c".  We added to the config.xml file the line:

<LOCAL host="hxv142c" >

Then, on hxv142c we did the following commands: 

xhost +hxgpu0

But when we ran OpenCOVER, the following errors resulted.  Any advice?  Apparently the missing shared objects are not on our system.  Thanks in advance.

558] [hxgpu0] $/hx/u/legts/covise/bin/opencover 
_exec_for_covise
coConfigRoot::setContentsFromDom info: ALREADY INCLUDED:  filename: config.xml
Compiled with OpenMP support, using a maximum of 1 threads
No PipeConfig for Pipe 0 found, using DISPLAY=:0
Input: Persons must be configured!
plugins: const
devices:
buttons: Mouse
bodies:
persons: num=1, active=default, head=0, hand=0

libScale.so: cannot open shared object file: No such file or directory
ERROR: could not load shared Library libScale.so

libViewerDistance.so: cannot open shared object file: No such file or directory
ERROR: could not load shared Library libViewerDistance.so

libFadeDistance.so: cannot open shared object file: No such file or directory
ERROR: could not load shared Library libFadeDistance.so
Plugins which failed to load: Scale ViewerDistance FadeDistance.
Error: Unable to open display ":0.0".
No valid Pixel Format found, trying without multisample Buffer
Error: Unable to open display ":0.0".
No valid Pixel Format found, trying without stencil
Error: Unable to open display ":0.0".
No valid Pixel Format found, trying without alpha
Error: Unable to open display ":0.0".
VRWindow::createWin 0 --- finished
Segmentation fault

**Comment by aumuell** [comment]
Sorry that I missed this issue for such a long time.

The following message indicates a problem where your COVISE/COVER configuration does not match your set up:
> No PipeConfig for Pipe 0 found, using DISPLAY=:0

Your set up is unusual, as you do not want to use the X server where you run OpenCOVER. Unfortunately, a PipeConfig won't help in your case, as OpenCOVER currently does not support reading a host for its X11 display from its config file.

One possible work-around could be to add the line
    <HonourDisplay value="true" />
to your `config.xml` somewhere within `<GLOBAL><COVER>`...`</COVER></GLOBAL>` and set `DISPLAY` according to your needs.
