### ISSUE TITLE
where to find the compiled lib and h files?

### ISSUE THREAD

**Issue by AnakinSkyCN** [hlrs-vis/covise#42]
Hi,

I've spent 2 weeks building the covise project. It seems too hard to do the right conifiguring to build it due to the long list of dependencies and tools.

Could you provide a compiled version of this project, with complete necessary .lib and .h files?

Thank you.

**Comment by uwewoessner** [comment]
You can download a compiled version for windows on https://www.hlrs.de/solutions-services/service-portfolio/visualization/covise/support/
We don't provide pre compiled versions for linux.
If you want to develop plugins and do require dependencies, you can send me a mail and I can provide you a zip file with all necessary dependencies.
Regards,
 Uwe

**Comment by AnakinSkyCN** [comment]
Please send me the windows version of dependencies to 21st_anakin@sina.com. Thank you.
The compiled application seems to contains only .lib files, but no .h files. I wonder do I still need the 3rd party dependencies in this situation.
A detailed building instruction in windows and VC would be a great help since the .bat and CMake files are confusing and failing sometimes.
Thank you very much.

**Comment by HolyBugger** [comment]
Also i need a zip file with all necessary dependencies on Linux to zhenwei.qian@hirain.com.
Thank you!
