### ISSUE TITLE
Configure ODDlot issue

### ISSUE THREAD

**Issue by liuziyi16** [hlrs-vis/covise#56]
When I try to configure ODDlot by using CMake,it comes to some problems,saying that Unknown CMake command "covise_find_package".

**Comment by aumuell** [comment]
cmake only works from the COVISE root directory, the directory which was created by 'get checkout'. Did you try it from there? If yes, then please reopen and provide more info.

Thank you,
Martin

**Comment by liuziyi16** [comment]
Thank you for your help.
If I want to  compile ODDLOT on Windows,I should download external libraries. And then I need to configure it in the COVISE root directory .
Is that right?
Would you like to provide me an archive with all the dependencies I require on Windows?
My mail address is 502228680@qq.com
Thanks a lot.
