### ISSUE TITLE
Oddlot Import Map issue

### ISSUE THREAD

**Issue by hsienyan** [hlrs-vis/covise#60]
Hi all

I tried to import google/bing map, I encountered SSL issue :
"one or more SSL errors has occurred,The issuer certificate...."

Anyone has idea regarding this ?

**Comment by uwewoessner** [comment]
I tried it out but Can't replicate the error, it is working fine here., Both with Google and Bing Maps

**Comment by aumuell** [comment]
Please reopen the issue with more information, if it is still not resolved.
