### ISSUE TITLE
when I run the oddlot, it is always inform me that Could not load prototypes.odd

### ISSUE THREAD

**Issue by TianTianHaoXinQing** [hlrs-vis/covise#62]
`project/covise-master/linux64opt/bin$ ./oddlot

Starting...
  ODDlot: The OpenDRIVE Designer for Lanes, Objects and Tracks.

Loading file: /share/covise/prototypes/prototypes.odd
Loading file failed: /share/covise/prototypes/prototypes.odd
Loading file: /src/OpenCOVER/DrivingSim/oddlot/prototypes/prototypes.odd
Loading file failed: /src/OpenCOVER/DrivingSim/oddlot/prototypes/prototypes.odd
Loading file: prototypes/prototypes.odd
Loading file failed: prototypes/prototypes.odd
Could not load prototypes.odd
`

**Comment by uwewoessner** [comment]
Hi Tian,
All you need to do is set the environment variable ODDLOTDIR or COVISEDIR to where you checked out covise.
Then it will find those files.

**Comment by TianTianHaoXinQing** [comment]
> Hi Tian,
> All you need to do is set the environment variable ODDLOTDIR or COVISEDIR to where you checked out covise.
> Then it will find those
up to now, I don`t know how to set the environment variable ODDLOTDIR or COVISEDIR to where I checked out covise, can you tell me how to do that , I will be very thankful to you!

**Comment by uwewoessner** [comment]
please replace the "..." with the absolute path to your project directory in the following line:
export COVISEDIR=.../project/covise-master
export PATH=$PATH:${COVISEDIR}/bin
oddlot

this should work.
you can add the two export lines to your .bashrc (or similar depending on your shell)

**Comment by TianTianHaoXinQing** [comment]
> export PATH=$PATH:${COVISEDIR}/bin

good job, thank you all the time my friend, I got it now under your advice. Thank you very much.

**Comment by TianTianHaoXinQing** [comment]
> please replace the "..." with the absolute path to your project directory in the following line:
> export COVISEDIR=.../project/covise-master
> export PATH=$PATH:${COVISEDIR}/bin
> oddlot
> 
> this should work.
> you can add the two export lines to your .bashrc (or similar depending on your shell)

Thank you all the time my friend, I got it now with your advice, thank you very much.

**Comment by TianTianHaoXinQing** [comment]
> please replace the "..." with the absolute path to your project directory in the following line:
> export COVISEDIR=.../project/covise-master
> export PATH=$PATH:${COVISEDIR}/bin
> oddlot
> 
> this should work.
> you can add the two export lines to your .bashrc (or similar depending on your shell)

hello，when I runing oddlot  and wanting to buil a new project, there is always confirming me that 
TODO ProfileGraph Scene size
WARNING 1003111729! ProjectWidget::mainEditorChanged() Editor unknown
WARNING 1003111729! ProjectWidget::mainEditorChanged() Editor unknown
WARNING 1003111729! ProjectWidget::mainEditorChanged() Editor unknown
WARNING 1003111729! ProjectWidget::mainEditorChanged() Editor unknown
WARNING 1003111729! ProjectWidget::mainEditorChanged() Editor unknown
WARNING 1003111729! ProjectWidget::mainEditorChanged() Editor unknown
