### ISSUE TITLE
oddlot does not exist

### ISSUE THREAD

**Issue by Basavaraj-PN** [hlrs-vis/covise#63]
I complied from source and I am getting this error, does this project requires CUDA or Nvidia?

**Comment by uwewoessner** [comment]
COVISE can be compiled with CUDA support but OddLOT does not need it. It is probably a different dependency which is missing.
If you look at the oddlot CMakeLists.txt you can see the dependencies required:
using(XercesC)
using(TIFF)
using(JPEG)
using(PROJ4)
USING(BOOST)
using(OpenScenario)
USING(OpenCRG)
using(EIGEN)
Check the cmake output to see which of these is missing.

**Comment by Basavaraj-PN** [comment]
> COVISE can be compiled with CUDA support but OddLOT does not need it. It is probably a different dependency which is missing.
> If you look at the oddlot CMakeLists.txt you can see the dependencies required:
> using(XercesC)
> using(TIFF)
> using(JPEG)
> using(PROJ4)
> USING(BOOST)
> using(OpenScenario)
> USING(OpenCRG)
> using(EIGEN)
> Check the cmake output to see which of these is missing.

yeah you are right, there are plenty of deps need to be installed :(
