### ISSUE TITLE
Unable to install the docker image

### ISSUE THREAD

**Issue by kanakab** [hlrs-vis/covise#64]
Hello All,

I tried to install the ODDLOT on my Ubuntu 18.04 using the Docker image here: https://github.com/hbanzhaf/docker_covise
I am getting the following error. Please help me to fix this error.

![Bildschirmfoto von 2020-09-11 16-00-34](https://user-images.githubusercontent.com/57012567/93057576-6fc15c80-f66e-11ea-89a9-d750cffa030e.png)

**Comment by aumuell** [comment]
I suspect that you did not execute the docker command from within the directory that was created by cloning docker_covise.
