### ISSUE TITLE
Covise Build Issue

### ISSUE THREAD

**Issue by Rjbeckwith55** [hlrs-vis/covise#67]
I am getting the following error when trying to make on my local Ubuntu 18.04 machine and using the docker_covise build.
```
~/Downloads/covise/src/3rdparty/visionaray/include/visionaray/math/simd/detail/avx512/mask16.inl:63:17: error: no matching function for call to 'store(int [16], const mask16&)'
     store(arr, a);
```
Any ideas on what the build issue could be?

**Comment by uwewoessner** [comment]
you don't need visionaray if you just want to compile OddLOT.
just set COVISE_USE_VISIONARAY to FALSE, then it should compile quicker and with less issues.
cmake ../.. -DCOVISE_WARNING_IS_ERROR=FALSE -DCOVISE_USE_VISIONARAY=FALSE
should do the trick

**Comment by Rjbeckwith55** [comment]
That did it! Thank you for the help!
