### ISSUE TITLE
oddlot opendrive editing tutorial

### ISSUE THREAD

**Issue by weidezhang** [hlrs-vis/covise#71]
Hi 
Is there an english version documentation on the usage of oddlot ?  For example, how shall we edit lane properties, length, change lane curve etc. Also what are the keyboard hot key to move the loaded map in the screen. Thank you,

**Comment by augri** [comment]
I would also be interested in any documentation and tutorials. Creating OpenDRIVE files from scratch as well as editing existing files.

**Comment by weidezhang** [comment]
i saw some document in germany but do you have english version of it? really appreciate it.

**Comment by aumuell** [comment]
I'm happy to report that there is some basic documentation, please find it here: https://fs.hlrs.de/projects/covise/doc/pdf/oddlot.pdf

It's also included in the repo since cd15afc80d0989f0ebbd0d3b2451f33a06e0708c

**Comment by Sultan91** [comment]
Is there a fresh link to the manual?

**Comment by uwewoessner** [comment]
If you checkout the repository , you find two documents in covise\src\oddlot\doc, one is the Master thesis in german and the other is a short english manual. I also fixed the above link. that should work again.
