### ISSUE TITLE
error: oddlot does not exist

### ISSUE THREAD

**Issue by wangxinchd** [hlrs-vis/covise#77]
After the successful compilation tool oddlot, I refer to https://github.com/hbanzhaf/docker_covise to execute oddlot, prompting /home/uisee/Downloads/covise/xerusopt/bin/oddlot does not exist.
If you execute ~/Downloads/covise/bin/_exec_for_covise, it prompts /home/uisee/Downloads/covise/bin/_exec_for_covise: line 149: /home/uisee/Downloads/covise/xerusopt/bin/: Is a directory
/home/uisee/Downloads/covise/bin/_exec_for_covise: line 149: exec: /home/uisee/Downloads/covise/xerusopt/bin/: cannot execute: Is a directory.
Excuse me, is there a release version of oddlot that can be used directly?
My operating system is ubuntu16.04

**Comment by aumuell** [comment]
We don't provide precompiled versions of COVISE and related tools except for Windows: https://fs.hlrs.de/projects/covise/support/download/

Unfortunately, it became not clear to me which steps you followed to run into the reported problem. Did you follow the instructions listed in https://github.com/hbanzhaf/docker_covise/blob/master/README.md ? Did you try to build everything from within the container? Did you also try to execute oddlot from within the container?

**Comment by aumuell** [comment]
I assume that your problem has been solved, as we didn't receive any follow-up.
