### ISSUE TITLE
Could oddlot load points

### ISSUE THREAD

**Issue by zqian4321** [hlrs-vis/covise#83]
I want to know whether oddlot supports load .txt file only containts points(xyz or xyzrgb).

**Comment by uwewoessner** [comment]
neighter of the two, OddLot can import Intermap Road files, csv tables of lat, lon, height tripples, car maker road files and OpenStreetMap files.
Did you mean OpenCOVER and it's PointCloud plugin? This can read and render xyzrgb files.

**Comment by zqian4321** [comment]
Ok, got it. Is there Oddlot`s PointCloud plugin?

**Comment by zqian4321** [comment]
Is there any tutorials of how to load the PointCloud in OpenCOVER and then link Oddlot to OpenCOVER. It seems that there is few tutorials about this.

**Comment by uwewoessner** [comment]
No, there is no totorial about this topic but I can help if you have specific questions.

**Comment by zqian4321** [comment]
I have installed the latest covise in Windows. But when i open .ply file in OpenCover, it seems nothing happened. So how to load and render PointCloulds. 
By the way, i find that ODDLot could import CSV Road, what is the format of CSV Road?

**Comment by uwewoessner** [comment]
OpenCOVER can't load pointclouds in ply format, only polygons.
You can convert your ply file to .e57 (or ptx or pts) then you can load the pointcloud.

Regarding CSV files:
it is a simple road centerline  in lat; lon; alt;
ProjectWidget::importCSVRoadFile(const QString &fileName)
int num = sscanf(line.toUtf8(), "%lf; %lf; %lf", &longitude, &latitude, &alt);

Regards,
 Uwe

**Comment by zqian4321** [comment]
Thank you for your patient help. 
I open 111.pts in opencover, it still seems that nothing happened.  The covise console outputs as follow：

PlugIn.PointCloud: call PointCloudInteractor()
PlugIn.PointCloud: call PointCloudInteractor()
ui::Owner: invalid name C:/Users/ASUS/Desktop/111.pts
failed to get line
Total num of points is 1785790
failed 2 to get line
Total num of valid points is 1785790
closing the file
avg fps: 0.0548246, min fps: 0.0548246

Why is this? Was .pts file loaded successfully?

**Comment by uwewoessner** [comment]
Do you have time for a chat? You can reach me here: https://unistuttgart.webex.com/meet/uwe.woessner
